using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LlamaBrain.Core.Expectancy
{
  /// <summary>
  /// A collection of constraints generated by the Expectancy Engine.
  /// Used by both the Prompt Assembler and the Validation Gate.
  /// </summary>
  [System.Serializable]
  public class ConstraintSet
  {
    private List<Constraint> _constraints = new List<Constraint>();

    /// <summary>
    /// All constraints in this set.
    /// </summary>
    public IReadOnlyList<Constraint> All => _constraints;

    /// <summary>
    /// All prohibition constraints.
    /// </summary>
    public IEnumerable<Constraint> Prohibitions =>
        _constraints.Where(c => c.Type == ConstraintType.Prohibition);

    /// <summary>
    /// All requirement constraints.
    /// </summary>
    public IEnumerable<Constraint> Requirements =>
        _constraints.Where(c => c.Type == ConstraintType.Requirement);

    /// <summary>
    /// All permission constraints.
    /// </summary>
    public IEnumerable<Constraint> Permissions =>
        _constraints.Where(c => c.Type == ConstraintType.Permission);

    /// <summary>
    /// Number of constraints in this set.
    /// </summary>
    public int Count => _constraints.Count;

    /// <summary>
    /// Whether this set has any constraints.
    /// </summary>
    public bool HasConstraints => _constraints.Count > 0;

    /// <summary>
    /// Adds a constraint to the set.
    /// </summary>
    /// <param name="constraint">The constraint to add</param>
    public void Add(Constraint constraint)
    {
      if (constraint != null && !_constraints.Any(c => c.Id == constraint.Id))
      {
        _constraints.Add(constraint);
      }
    }

    /// <summary>
    /// Adds multiple constraints to the set.
    /// </summary>
    /// <param name="constraints">The constraints to add</param>
    public void AddRange(IEnumerable<Constraint> constraints)
    {
      foreach (var constraint in constraints)
      {
        Add(constraint);
      }
    }

    /// <summary>
    /// Removes a constraint by ID.
    /// </summary>
    /// <param name="constraintId">The ID of the constraint to remove</param>
    /// <returns>True if the constraint was found and removed, false otherwise</returns>
    public bool Remove(string constraintId)
    {
      return _constraints.RemoveAll(c => c.Id == constraintId) > 0;
    }

    /// <summary>
    /// Checks if a constraint with the given ID exists.
    /// </summary>
    /// <param name="constraintId">The ID of the constraint to check</param>
    /// <returns>True if a constraint with the given ID exists, false otherwise</returns>
    public bool Contains(string constraintId)
    {
      return _constraints.Any(c => c.Id == constraintId);
    }

    /// <summary>
    /// Gets a constraint by ID.
    /// </summary>
    /// <param name="constraintId">The ID of the constraint to retrieve</param>
    /// <returns>The constraint with the given ID, or null if not found</returns>
    public Constraint Get(string constraintId)
    {
      return _constraints.FirstOrDefault(c => c.Id == constraintId);
    }

    /// <summary>
    /// Clears all constraints.
    /// </summary>
    public void Clear()
    {
      _constraints.Clear();
    }

    /// <summary>
    /// Generates the prompt injection text for all constraints.
    /// This text should be inserted into the system prompt.
    /// </summary>
    /// <returns>A formatted string containing all constraint prompt injections</returns>
    public string ToPromptInjection()
    {
      if (!HasConstraints) return string.Empty;

      var sb = new StringBuilder();
      sb.AppendLine("\n[CONSTRAINTS]");

      var prohibitions = Prohibitions.ToList();
      if (prohibitions.Count > 0)
      {
        sb.AppendLine("You must NOT:");
        foreach (var p in prohibitions)
        {
          sb.AppendLine($"- {p.PromptInjection}");
        }
      }

      var requirements = Requirements.ToList();
      if (requirements.Count > 0)
      {
        sb.AppendLine("You MUST:");
        foreach (var r in requirements)
        {
          sb.AppendLine($"- {r.PromptInjection}");
        }
      }

      var permissions = Permissions.ToList();
      if (permissions.Count > 0)
      {
        sb.AppendLine("You MAY:");
        foreach (var p in permissions)
        {
          sb.AppendLine($"- {p.PromptInjection}");
        }
      }

      sb.AppendLine("[/CONSTRAINTS]");
      return sb.ToString();
    }

    /// <summary>
    /// Creates an empty constraint set.
    /// </summary>
    public static ConstraintSet Empty => new ConstraintSet();

    /// <summary>
    /// Returns a string representation of this constraint set.
    /// </summary>
    /// <returns>A formatted string showing the count of each constraint type</returns>
    public override string ToString()
    {
      return $"ConstraintSet[{Prohibitions.Count()} prohibitions, {Requirements.Count()} requirements, {Permissions.Count()} permissions]";
    }
  }
}
