using System;
using System.Collections.Generic;
using LlamaBrain.Core.Expectancy;

namespace LlamaBrain.Core.Inference
{
  /// <summary>
  /// An immutable snapshot of all context at inference time.
  /// Used to ensure consistent state across retry attempts.
  /// This is box 4 in the architecture: "Authoritative State Snapshot".
  /// </summary>
  [Serializable]
  public class StateSnapshot
  {
    /// <summary>
    /// Unique identifier for this snapshot.
    /// </summary>
    public string SnapshotId { get; }

    /// <summary>
    /// When this snapshot was created.
    /// </summary>
    public DateTime CreatedAt { get; }

    /// <summary>
    /// The interaction context that triggered this inference.
    /// </summary>
    public InteractionContext Context { get; }

    /// <summary>
    /// The constraints generated by the Expectancy Engine.
    /// </summary>
    public ConstraintSet Constraints { get; }

    /// <summary>
    /// Retrieved canonical facts relevant to this interaction.
    /// </summary>
    public IReadOnlyList<string> CanonicalFacts { get; }

    /// <summary>
    /// Retrieved world state relevant to this interaction.
    /// </summary>
    public IReadOnlyList<string> WorldState { get; }

    /// <summary>
    /// Retrieved episodic memories relevant to this interaction.
    /// </summary>
    public IReadOnlyList<string> EpisodicMemories { get; }

    /// <summary>
    /// Retrieved beliefs relevant to this interaction.
    /// </summary>
    public IReadOnlyList<string> Beliefs { get; }

    /// <summary>
    /// Recent dialogue history for context.
    /// </summary>
    public IReadOnlyList<string> DialogueHistory { get; }

    /// <summary>
    /// The persona's system prompt / character description.
    /// </summary>
    public string SystemPrompt { get; }

    /// <summary>
    /// The player's input that triggered this interaction.
    /// </summary>
    public string PlayerInput { get; }

    /// <summary>
    /// Current retry attempt (0 = first attempt).
    /// </summary>
    public int AttemptNumber { get; }

    /// <summary>
    /// Maximum allowed retry attempts.
    /// </summary>
    public int MaxAttempts { get; }

    /// <summary>
    /// Additional metadata for debugging/logging.
    /// </summary>
    public IReadOnlyDictionary<string, string> Metadata { get; }

    /// <summary>
    /// Creates a new immutable state snapshot.
    /// Use StateSnapshotBuilder for construction.
    /// </summary>
    /// <param name="snapshotId">Unique identifier for this snapshot</param>
    /// <param name="context">The interaction context that triggered this inference</param>
    /// <param name="constraints">The constraints generated by the Expectancy Engine</param>
    /// <param name="canonicalFacts">Retrieved canonical facts relevant to this interaction</param>
    /// <param name="worldState">Retrieved world state relevant to this interaction</param>
    /// <param name="episodicMemories">Retrieved episodic memories relevant to this interaction</param>
    /// <param name="beliefs">Retrieved beliefs relevant to this interaction</param>
    /// <param name="dialogueHistory">Recent dialogue history for context</param>
    /// <param name="systemPrompt">The persona's system prompt / character description</param>
    /// <param name="playerInput">The player's input that triggered this interaction</param>
    /// <param name="attemptNumber">Current retry attempt (0 = first attempt)</param>
    /// <param name="maxAttempts">Maximum allowed retry attempts</param>
    /// <param name="metadata">Additional metadata for debugging/logging (optional)</param>
    internal StateSnapshot(
      string snapshotId,
      InteractionContext context,
      ConstraintSet constraints,
      IReadOnlyList<string> canonicalFacts,
      IReadOnlyList<string> worldState,
      IReadOnlyList<string> episodicMemories,
      IReadOnlyList<string> beliefs,
      IReadOnlyList<string> dialogueHistory,
      string systemPrompt,
      string playerInput,
      int attemptNumber,
      int maxAttempts,
      IReadOnlyDictionary<string, string>? metadata)
    {
      SnapshotId = snapshotId;
      CreatedAt = DateTime.UtcNow;
      Context = context;
      Constraints = constraints;
      CanonicalFacts = canonicalFacts;
      WorldState = worldState;
      EpisodicMemories = episodicMemories;
      Beliefs = beliefs;
      DialogueHistory = dialogueHistory;
      SystemPrompt = systemPrompt;
      PlayerInput = playerInput;
      AttemptNumber = attemptNumber;
      MaxAttempts = maxAttempts;
      Metadata = metadata ?? new Dictionary<string, string>();
    }

    /// <summary>
    /// Creates a new snapshot for a retry attempt with updated constraints.
    /// The new snapshot will have an incremented attempt number and a new snapshot ID.
    /// All constraints from the current snapshot are preserved, with additional constraints merged in.
    /// </summary>
    /// <param name="additionalConstraints">Extra constraints for stricter retry (optional)</param>
    /// <returns>A new StateSnapshot instance with incremented attempt number and merged constraints</returns>
    public StateSnapshot ForRetry(ConstraintSet? additionalConstraints = null)
    {
      var newConstraints = new ConstraintSet();
      newConstraints.AddRange(Constraints.All);

      if (additionalConstraints != null)
      {
        newConstraints.AddRange(additionalConstraints.All);
      }

      return new StateSnapshot(
        snapshotId: Guid.NewGuid().ToString("N")[..8],
        context: Context,
        constraints: newConstraints,
        canonicalFacts: CanonicalFacts,
        worldState: WorldState,
        episodicMemories: EpisodicMemories,
        beliefs: Beliefs,
        dialogueHistory: DialogueHistory,
        systemPrompt: SystemPrompt,
        playerInput: PlayerInput,
        attemptNumber: AttemptNumber + 1,
        maxAttempts: MaxAttempts,
        metadata: Metadata
      );
    }

    /// <summary>
    /// Whether more retry attempts are allowed.
    /// </summary>
    public bool CanRetry => AttemptNumber < MaxAttempts - 1;

    /// <summary>
    /// Gets all memory as a combined list for prompt injection.
    /// Formats each memory type with appropriate prefixes: [Fact] for canonical facts, [State] for world state, [Memory] for episodic memories.
    /// Beliefs are returned without prefixes.
    /// </summary>
    /// <returns>An enumerable collection of formatted memory strings ready for prompt injection</returns>
    public IEnumerable<string> GetAllMemoryForPrompt()
    {
      foreach (var fact in CanonicalFacts) yield return $"[Fact] {fact}";
      foreach (var state in WorldState) yield return $"[State] {state}";
      foreach (var memory in EpisodicMemories) yield return $"[Memory] {memory}";
      foreach (var belief in Beliefs) yield return belief;
    }

    /// <summary>
    /// Gets the total memory item count.
    /// </summary>
    public int TotalMemoryCount =>
      CanonicalFacts.Count + WorldState.Count + EpisodicMemories.Count + Beliefs.Count;

    /// <summary>
    /// Returns a string representation of this state snapshot.
    /// </summary>
    /// <returns>A formatted string showing the snapshot ID, attempt number, memory count, and constraint count</returns>
    public override string ToString()
    {
      return $"StateSnapshot[{SnapshotId}] Attempt {AttemptNumber + 1}/{MaxAttempts}, " +
             $"{TotalMemoryCount} memories, {Constraints.Count} constraints";
    }
  }

  /// <summary>
  /// Builder for creating StateSnapshot instances.
  /// </summary>
  public class StateSnapshotBuilder
  {
    private InteractionContext? _context;
    private ConstraintSet _constraints = new ConstraintSet();
    private List<string> _canonicalFacts = new List<string>();
    private List<string> _worldState = new List<string>();
    private List<string> _episodicMemories = new List<string>();
    private List<string> _beliefs = new List<string>();
    private List<string> _dialogueHistory = new List<string>();
    private string _systemPrompt = "";
    private string _playerInput = "";
    private int _attemptNumber = 0;
    private int _maxAttempts = 3;
    private Dictionary<string, string> _metadata = new Dictionary<string, string>();

    /// <summary>
    /// Sets the interaction context that triggered this inference.
    /// </summary>
    /// <param name="context">The interaction context to set</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithContext(InteractionContext context)
    {
      _context = context;
      return this;
    }

    /// <summary>
    /// Sets the constraints generated by the Expectancy Engine.
    /// </summary>
    /// <param name="constraints">The constraint set to use</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithConstraints(ConstraintSet constraints)
    {
      _constraints = constraints;
      return this;
    }

    /// <summary>
    /// Adds canonical facts relevant to this interaction.
    /// Canonical facts are immutable truths that cannot be contradicted.
    /// </summary>
    /// <param name="facts">The canonical facts to add</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithCanonicalFacts(IEnumerable<string> facts)
    {
      _canonicalFacts.AddRange(facts);
      return this;
    }

    /// <summary>
    /// Adds world state entries relevant to this interaction.
    /// World state represents mutable game state that can change.
    /// </summary>
    /// <param name="state">The world state entries to add</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithWorldState(IEnumerable<string> state)
    {
      _worldState.AddRange(state);
      return this;
    }

    /// <summary>
    /// Adds episodic memories relevant to this interaction.
    /// Episodic memories represent conversation and event history.
    /// </summary>
    /// <param name="memories">The episodic memories to add</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithEpisodicMemories(IEnumerable<string> memories)
    {
      _episodicMemories.AddRange(memories);
      return this;
    }

    /// <summary>
    /// Adds beliefs relevant to this interaction.
    /// Beliefs are mutable and can be wrong; they may change based on interactions.
    /// </summary>
    /// <param name="beliefs">The beliefs to add</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithBeliefs(IEnumerable<string> beliefs)
    {
      _beliefs.AddRange(beliefs);
      return this;
    }

    /// <summary>
    /// Adds recent dialogue history for context.
    /// </summary>
    /// <param name="history">The dialogue history entries to add</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithDialogueHistory(IEnumerable<string> history)
    {
      _dialogueHistory.AddRange(history);
      return this;
    }

    /// <summary>
    /// Sets the persona's system prompt / character description.
    /// </summary>
    /// <param name="prompt">The system prompt to set</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithSystemPrompt(string prompt)
    {
      _systemPrompt = prompt;
      return this;
    }

    /// <summary>
    /// Sets the player's input that triggered this interaction.
    /// </summary>
    /// <param name="input">The player's input text</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithPlayerInput(string input)
    {
      _playerInput = input;
      return this;
    }

    /// <summary>
    /// Sets the current retry attempt number (0 = first attempt).
    /// </summary>
    /// <param name="attempt">The attempt number to set</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithAttemptNumber(int attempt)
    {
      _attemptNumber = attempt;
      return this;
    }

    /// <summary>
    /// Sets the maximum allowed retry attempts.
    /// </summary>
    /// <param name="max">The maximum number of attempts allowed</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithMaxAttempts(int max)
    {
      _maxAttempts = max;
      return this;
    }

    /// <summary>
    /// Adds or updates a metadata entry for debugging/logging purposes.
    /// </summary>
    /// <param name="key">The metadata key</param>
    /// <param name="value">The metadata value</param>
    /// <returns>This builder instance for method chaining</returns>
    public StateSnapshotBuilder WithMetadata(string key, string value)
    {
      _metadata[key] = value;
      return this;
    }

    /// <summary>
    /// Builds and returns a new immutable StateSnapshot instance.
    /// If no context was provided, creates a default InteractionContext.
    /// Generates a new unique snapshot ID automatically.
    /// </summary>
    /// <returns>A new immutable StateSnapshot instance with all configured values</returns>
    public StateSnapshot Build()
    {
      if (_context == null)
      {
        _context = new InteractionContext();
      }

      return new StateSnapshot(
        snapshotId: Guid.NewGuid().ToString("N")[..8],
        context: _context,
        constraints: _constraints,
        canonicalFacts: _canonicalFacts.AsReadOnly(),
        worldState: _worldState.AsReadOnly(),
        episodicMemories: _episodicMemories.AsReadOnly(),
        beliefs: _beliefs.AsReadOnly(),
        dialogueHistory: _dialogueHistory.AsReadOnly(),
        systemPrompt: _systemPrompt,
        playerInput: _playerInput,
        attemptNumber: _attemptNumber,
        maxAttempts: _maxAttempts,
        metadata: _metadata
      );
    }
  }
}
